SOUND: when loading an external ambient sound a lockup occurs
QW-Group/ezquake-source pull request #723
Opened 2022-12-23 21:20 UTC by ciscon

SOUND: when loading an external ambient sound (eg water1.wav), in S_ParseCueMark where it calls BuffLittleLong, it always returns the size as 0, causing it to loop forever

2022-12-23 21:30 UTC, ciscon commented
it leaves ambient sounds broken with external sounds, so there's definitely a break in the way they are being handled in general, but at least it doesn't lock up.  using the old wav loading works.

2022-12-24 10:43 UTC, dsvensson commented
Sweet, I actually hit this as well when running crmod on ftesv and connecting with ezq. The map in question uses `ambient_general` that resulted in ezquake freezing on connect. This PR fixes that issue.

2022-12-24 11:35 UTC, hemostx commented
Ooh, I wonder how that plays with #671 (remastered ambient loops don't play anymore) which is a result of 95f4f98203be115994ef82fe12c8eb1cd6a31a5e - (Fixed playback of looping sounds when using libsndfile to load sounds (reported by lurq)).

I can only check if this impacts #671, as I did not encounter the issue fixed by 95f4f98203be115994ef82fe12c8eb1cd6a31a5e.

2022-12-25 22:04 UTC, tcsabina requested changes

2022-12-25 22:04 UTC, tcsabina commented on snd_mem.c
> +	while (pos < len - 8 && size !=0 ) {
Can you add some braces around the logical operations, please?

Also, there should be a space before 0, and nospace before the closing brace ;)

2023-01-02 19:30 UTC, tcsabina commented
@ciscon ,
Can you add those cosmetic changes?

2023-01-02 19:48 UTC, tcsabina approved these changes

2023-01-02 19:48 UTC, merged